# Generated by Django 5.1.1 on 2024-09-16 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_experiencemodel_interestmodel_languagemodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumemodel',
            old_name='grndrt_type',
            new_name='gender_type',
        ),
    ]
