# Generated by Django 5.1.1 on 2024-09-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_rename_grndrt_type_resumemodel_gender_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intermediate_skill_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
